import { env } from "cloudflare:workers";

type Db = { prepare: (sql: string) => { bind: (...v: unknown[]) => { first: <T>() => Promise<T | null>; all: <T>() => Promise<{ results: T[] }>; run: () => Promise<unknown> } }; batch: (items: unknown[]) => Promise<unknown> };
type Runtime = { DB: Db; ARK_API_KEY?: string; OPENROUTER_API_KEY?: string; TEACHER_ACCESS_CODE?: string };
const runtime = env as unknown as Runtime;
const now = () => new Date().toISOString();
const json = (body: unknown, status = 200) => Response.json(body, { status, headers: { "access-control-allow-origin": "https://theonlywind.github.io", "access-control-allow-headers": "content-type,x-teacher-code", "access-control-allow-methods": "GET,POST,PATCH,OPTIONS", vary: "Origin" } });
const hash = async (v: string) => Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(v)))).map((x) => x.toString(16).padStart(2, "0")).join("");
const clean = (v: unknown, max = 500) => typeof v === "string" ? v.trim().slice(0, max) : "";
const db = () => runtime.DB;
const bad = (v: string) => /住址|地址|電話|tel|phone|裸體|色情|血腥|成人|裸露/i.test(v);
async function schema() { const stamp = now(); await db().batch([
  db().prepare("CREATE TABLE IF NOT EXISTS class_codes (id TEXT PRIMARY KEY, code_hash TEXT NOT NULL UNIQUE, label TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL)").bind(),
  db().prepare("CREATE TABLE IF NOT EXISTS class_students (id TEXT PRIMARY KEY, code_id TEXT NOT NULL UNIQUE, display_name TEXT NOT NULL, video_limit INTEGER NOT NULL DEFAULT 5, video_used INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL DEFAULT 'active', created_at TEXT NOT NULL, updated_at TEXT NOT NULL)").bind(),
  db().prepare("CREATE TABLE IF NOT EXISTS video_jobs (id TEXT PRIMARY KEY, student_id TEXT NOT NULL, provider_task_id TEXT NOT NULL UNIQUE, prompt TEXT NOT NULL, status TEXT NOT NULL, video_url TEXT, error_message TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)").bind(),
]); return stamp; }
function teacher(request: Request, bodyCode?: unknown) {
  const supplied = clean(request.headers.get("x-teacher-code") || bodyCode, 128);
  const configured = clean(runtime.TEACHER_ACCESS_CODE, 128);
  return Boolean(configured) && supplied === configured;
}
async function student(code: string) { const codeHash = await hash(code.toUpperCase()); return db().prepare("SELECT s.*, c.active AS code_active FROM class_codes c LEFT JOIN class_students s ON s.code_id=c.id WHERE c.code_hash=?").bind(codeHash).first<any>(); }
function view(s: any) { return { id:s.id, displayName:s.display_name, videoLimit:s.video_limit, videoUsed:s.video_used, status:s.status }; }
function code() { return `MOVIE-${Math.floor(100 + Math.random() * 900)}-${crypto.getRandomValues(new Uint32Array(1))[0].toString(36).slice(0, 4).toUpperCase()}`; }

const apiPath = (request: Request) => new URL(request.url).pathname.replace(/^\/api\/?/, "");
export function OPTIONS() { return new Response(null, { headers: { "access-control-allow-origin": "https://theonlywind.github.io", "access-control-allow-headers": "content-type,x-teacher-code", "access-control-allow-methods": "GET,POST,PATCH,OPTIONS", vary: "Origin" } }); }

export async function GET(request: Request, { params: _params }: { params: Promise<{ path: string[] }> }) { await schema(); const path = apiPath(request); const url = new URL(request.url);
  if (path === "teacher/students") { if (!teacher(request)) return json({ error:"教師代碼不正確。" },401); const rows = await db().prepare("SELECT s.*, c.label FROM class_students s JOIN class_codes c ON c.id=s.code_id ORDER BY s.created_at DESC").bind().all<any>(); return json({ students:rows.results.map(view) }); }
  if (path.startsWith("video/")) { const jobId = path.slice(6); const job = await db().prepare("SELECT * FROM video_jobs WHERE id=?").bind(jobId).first<any>(); if (!job) return json({ error:"找不到影片工作。" },404); if (["succeeded","failed"].includes(job.status)) return json({ job }); if (!runtime.ARK_API_KEY) return json({ error:"未設定 ARK_API_KEY。" },503);
    const result = await fetch(`https://ark.ap-southeast.bytepluses.com/api/v3/contents/generations/tasks/${job.provider_task_id}`,{headers:{Authorization:`Bearer ${runtime.ARK_API_KEY}`}}); const data:any = await result.json().catch(()=>({})); if (!result.ok) return json({ error:"暫時未能查詢影片狀態。" },502); const status = data.status || job.status; const videoUrl=data.content?.video_url || null; const error=data.error?.message || null; await db().prepare("UPDATE video_jobs SET status=?, video_url=?, error_message=?, updated_at=? WHERE id=?").bind(status,videoUrl,error,now(),jobId).run(); return json({ job:{...job,status,video_url:videoUrl,error_message:error} }); }
  return json({ error:"找不到服務。" },404);
}

export async function POST(request: Request, { params: _params }: { params: Promise<{ path: string[] }> }) { await schema(); const path=apiPath(request); const body=await request.json().catch(()=>({}));
  if (path === "join") { const displayName=clean(body.displayName,18), classCode=clean(body.classCode,32).toUpperCase(); if (!displayName || !classCode || bad(displayName)) return json({error:"請輸入創作暱稱及正確學生代碼。"},400); const found=await student(classCode); if (!found || !found.code_active) return json({error:"學生代碼不正確或已停用。"},401); if (found.id) return json({student:view(found)}); const id=crypto.randomUUID(); await db().prepare("INSERT INTO class_students (id,code_id,display_name,created_at,updated_at) VALUES (?,?,?,?,?)").bind(id,found.code_id,displayName,now(),now()).run(); return json({student:{id,displayName,videoLimit:5,videoUsed:0,status:"active"}},201); }
  if (path === "teacher/codes") { if (!teacher(request, body.teacherCode)) return json({error:"教師代碼不正確。"},401); const count=Math.min(30,Math.max(1,Number(body.count)||10)); const codes:string[]=[]; for(let i=0;i<count;i+=1){const plain=code();codes.push(plain);await db().prepare("INSERT INTO class_codes (id,code_hash,label,created_at) VALUES (?,?,?,?)").bind(crypto.randomUUID(),await hash(plain),`學生 ${i+1}`,now()).run();} return json({codes},201); }
  if (path === "image") { const prompt=clean(body.prompt,700), classCode=clean(body.classCode,32).toUpperCase(); if (!runtime.OPENROUTER_API_KEY) return json({error:"未設定圖片生成服務。"},503); if (prompt.length<8||bad(prompt)) return json({error:"請使用原創、兒童友善描述，且不要輸入個人資料。"},400); const s=await student(classCode); if(!s?.id||s.status!=="active")return json({error:"學生帳戶不可使用。"},403); const response=await fetch("https://openrouter.ai/api/v1/images",{method:"POST",headers:{Authorization:`Bearer ${runtime.OPENROUTER_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:"black-forest-labs/flux.2-klein-4b",output_format:"png",prompt:`Original child-friendly animation still, no real people, no logos, no words, no watermark. ${prompt}`})}); const data:any=await response.json().catch(()=>({})); const b64=data?.data?.[0]?.b64_json; if(!response.ok||!b64)return json({error:"圖片暫時未能生成，請稍後再試。"},502); return json({image:`data:image/png;base64,${b64}`}); }
  if (path === "video") { const classCode=clean(body.classCode,32).toUpperCase(), prompt=clean(body.prompt,800), firstFrame=clean(body.firstFrame,10_000_000), lastFrame=clean(body.lastFrame,10_000_000); if(!runtime.ARK_API_KEY)return json({error:"未設定 ARK_API_KEY。"},503); if(!firstFrame.startsWith("data:image/")||!lastFrame.startsWith("data:image/")||prompt.length<8||bad(prompt))return json({error:"請先生成兩張原創、兒童友善圖片。"},400); const s=await student(classCode); if(!s?.id||s.status!=="active")return json({error:"學生帳戶不可使用。"},403); if(s.video_used>=s.video_limit)return json({error:"你的 5 次影片配額已用完，請找老師協助。"},429);
    const response=await fetch("https://ark.ap-southeast.bytepluses.com/api/v3/contents/generations/tasks",{method:"POST",headers:{Authorization:`Bearer ${runtime.ARK_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:"dreamina-seedance-2-0-mini-260615",content:[{type:"text",text:prompt},{type:"image_url",image_url:{url:firstFrame},role:"first_frame"},{type:"image_url",image_url:{url:lastFrame},role:"last_frame"}],resolution:"480p",ratio:"16:9",duration:10,watermark:false,generate_audio:false,safety_identifier:s.id})}); const result:any=await response.json().catch(()=>({})); if(!response.ok||!result.id)return json({error:result?.error?.message||"影片未能開始；這次不會扣配額。"},502); const jobId=crypto.randomUUID(); await db().batch([db().prepare("UPDATE class_students SET video_used=video_used+1,updated_at=? WHERE id=?").bind(now(),s.id),db().prepare("INSERT INTO video_jobs (id,student_id,provider_task_id,prompt,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?)").bind(jobId,s.id,result.id,prompt,"queued",now(),now())]); return json({jobId,videoUsed:s.video_used+1,videoLimit:s.video_limit},202); }
  return json({error:"找不到服務。"},404);
}

export async function PATCH(request: Request, { params: _params }: { params: Promise<{ path: string[] }> }) { await schema(); if(apiPath(request)!=="teacher/students"||!teacher(request))return json({error:"未授權。"},401); const body=await request.json().catch(()=>({})), id=clean(body.id,100), action=clean(body.action,20); if(action==="reset")await db().prepare("UPDATE class_students SET video_used=0,updated_at=? WHERE id=?").bind(now(),id).run(); else if(action==="bonus")await db().prepare("UPDATE class_students SET video_limit=video_limit+1,updated_at=? WHERE id=?").bind(now(),id).run(); else if(action==="toggle")await db().prepare("UPDATE class_students SET status=CASE status WHEN 'active' THEN 'paused' ELSE 'active' END,updated_at=? WHERE id=?").bind(now(),id).run(); else return json({error:"無效操作。"},400); return json({ok:true}); }
