"use client";

import { useMemo, useState } from "react";

const choices = {
  hero: ["小貓", "小狗", "小兔", "小熊", "機械人", "小恐龍", "小怪獸", "小龍", "魔法小孩", "太空人", "海盜", "小精靈"],
  place: ["彩虹森林", "海底世界", "太空站", "月球", "魔法學校", "糖果城市", "雨天街道", "雲上城堡", "沙漠綠洲", "雪山", "恐龍島", "未來香港"],
  prop: ["一把神奇雨傘", "一個發光背包", "一張藏寶圖", "一枝魔法棒", "一個小火箭", "一盞星星燈", "一個生日蛋糕", "一個機械小球", "一朵會說話的花", "一個寶箱"],
  event: ["發現一扇魔法門", "遇到一位新朋友", "找到發光寶物", "追著一隻蝴蝶", "打開神奇雨傘", "聽到求救聲", "收到神秘地圖", "救出迷路的小動物", "看見流星雨", "按下一個紅色按鈕", "打開生日禮物", "發現會說話的書"],
  ending: ["飛到彩虹天空", "到達一座雲上城堡", "和朋友一起跳舞", "變成勇敢的小英雄", "找到一片星光海", "把寶物送回家", "讓城市重現色彩", "坐上魔法火車", "回到溫暖的家", "得到一枚勇氣徽章", "和新朋友擊掌", "打開新的冒險大門"],
  style: ["3D 兒童動畫", "明亮卡通插畫", "積木玩具世界", "柔和水彩動畫", "可愛像素遊戲", "彩色黏土動畫", "手繪童話書", "紙藝剪貼畫", "夢幻日系動畫", "復古漫畫"],
  action: ["慢慢向前走", "輕輕飛上天空", "轉身望向鏡頭", "打開手中的物品", "和朋友揮手", "開心地跳起來", "跑向遠處", "伸手接住光點", "從門後探出頭", "騎著單車前進"],
  camera: ["鏡頭輕輕跟隨", "鏡頭由下向上移動", "鏡頭慢慢拉遠", "鏡頭慢慢靠近", "鏡頭由左向右移動", "鏡頭從主角背後跟拍", "畫面輕輕旋轉", "鏡頭固定不動"],
};
type Key = keyof typeof choices;
const first = Object.fromEntries(Object.entries(choices).map(([key, values]) => [key, values[0]])) as Record<Key, string>;
const empty = Object.fromEntries(Object.keys(choices).map((key) => [key, ""])) as Record<Key, string>;
const labels: Record<Key, [string, string]> = { hero:["🧑‍🚀","誰是主角？"], place:["📍","故事在哪裏開始？"], prop:["🎒","主角帶著甚麼？"], event:["✨","一開始發生甚麼？"], ending:["🏁","最後會怎樣？"], style:["🎨","選擇畫風"], action:["🎞️","影片中的動作"], camera:["📹","鏡頭怎樣拍？"] };

export default function Home() {
  const [picked, setPicked] = useState<Record<Key, string>>(first); const [custom, setCustom] = useState<Record<Key, string>>(empty); const [title, setTitle] = useState("我的小電影"); const [copied, setCopied] = useState("");
  const value = (key: Key) => custom[key].trim() || picked[key];
  const startPrompt = useMemo(() => `請生成一張 ${value("style")}、兒童友善、16:9 橫向的圖片：${value("hero")} 在 ${value("place")}，帶著 ${value("prop")}，${value("event")}。畫面明亮、角色表情清楚、沒有文字、沒有水印。`, [picked, custom]);
  const endPrompt = useMemo(() => `請生成一張 ${value("style")}、兒童友善、16:9 橫向的圖片：${value("hero")} 帶著 ${value("prop")}，${value("ending")}。和第一張圖保持相同角色、服裝和畫風；畫面明亮、沒有文字、沒有水印。`, [picked, custom]);
  const videoPrompt = useMemo(() => `${value("hero")} 在 ${value("place")} ${value("action")}，帶著 ${value("prop")}，因為 ${value("event")}，最後 ${value("ending")}。動作自然連續，${value("camera")}，保持 ${value("style")}，不加文字。`, [picked, custom]);
  async function copy(label:string, text:string) { await navigator.clipboard.writeText(text); setCopied(label); window.setTimeout(() => setCopied(""), 1800); }
  return <main><header className="topbar"><div className="brand"><span>▶</span><div><strong>小小 AI 電影工作室</strong><small>兩張圖，變成一段小電影</small></div></div><div className="header-tip">先揀選，再生成</div></header><section className="hero"><div><p className="eyebrow">最後一堂・AI 影片創作</p><h1>你的故事，<br/><em>現在開拍！</em></h1><p>先選圖卡；如果找不到想要的，也可在「自己想一個」填短短的詞語。</p></div><div className="movie-card"><span className="clap">🎬</span><b>第 1 張圖</b><i>故事開始</i><div className="arrow">↓</div><b>第 2 張圖</b><i>精彩結局</i></div></section><section className="workflow" aria-label="電影創作步驟"><div className="step active"><span>1</span> 揀故事圖卡</div><div className="line"/><div className="step"><span>2</span> 生成兩張圖</div><div className="line"/><div className="step"><span>3</span> 製作影片</div></section><section className="builder"><div className="picker-panel"><p className="eyebrow">步驟 1</p><h2>揀選你的故事</h2><p className="soft">每一行可揀圖卡，或只輸入一兩個自訂詞語。</p>{(Object.keys(choices) as Key[]).map((key) => <Choice key={key} icon={labels[key][0]} title={labels[key][1]} values={choices[key]} selected={picked[key]} customValue={custom[key]} onChoose={(v) => setPicked((old) => ({...old,[key]:v}))} onCustom={(v) => setCustom((old) => ({...old,[key]:v}))}/>)}</div><aside className="plan-panel"><p className="eyebrow">你的故事</p><label>電影名稱<input value={title} maxLength={18} onChange={(e) => setTitle(e.target.value)} /></label><div className="storyboard"><div className="frame start"><span>第 1 幀・開始</span><strong>{value("hero")}</strong><small>{value("place")}<br/>{value("event")}</small></div><div className="frame end"><span>最後 1 幀・結局</span><strong>{value("hero")}</strong><small>{value("ending")}</small></div></div><p className="say-it">我拍的《{title || "我的小電影"}》：{value("hero")} 在 {value("place")}，帶著 {value("prop")}，最後 {value("ending")}！</p></aside></section><section className="make-section"><div><p className="eyebrow">步驟 2</p><h2>生成兩張關鍵圖片</h2><p>把提示詞複製到老師指定的 AI 繪圖工具。完成後，下載並保留兩張橫向圖片。</p></div><PromptCard number="A" title="生成第 1 幀：故事開始" text={startPrompt} copied={copied === "首幀"} onCopy={() => copy("首幀", startPrompt)}/><PromptCard number="B" title="生成最後 1 幀：故事結局" text={endPrompt} copied={copied === "尾幀"} onCopy={() => copy("尾幀", endPrompt)}/></section><section className="video-section"><div><p className="eyebrow">步驟 3</p><h2>讓兩張圖動起來</h2><p>在老師指定的 AI 影片工具，上載「第 1 幀」和「最後 1 幀」，然後貼上以下影片指示。</p></div><PromptCard number="▶" title="影片動作指示" text={videoPrompt} copied={copied === "影片"} onCopy={() => copy("影片", videoPrompt)}/><div className="checklist"><h3>交片前檢查</h3><p>□ 兩張圖都是橫向</p><p>□ 主角在兩張圖中看起來一樣</p><p>□ 沒有個人資料、校名或真實相片</p><p>□ 影片能播放</p></div></section><footer>小小 AI 電影工作室　•　AI 會幫忙，但故事是你創作的。</footer></main>;
}
function Choice({ title, icon, values, selected, customValue, onChoose, onCustom }: { title:string; icon:string; values:readonly string[]; selected:string; customValue:string; onChoose:(value:string)=>void; onCustom:(value:string)=>void }) { return <fieldset className="choice"><legend>{icon} {title}</legend><div>{values.map((value) => <button type="button" className={!customValue && selected === value ? "picked" : ""} onClick={() => onChoose(value)} key={value}>{value}</button>)}</div><label style={{display:"flex",gap:8,marginTop:11,alignItems:"center",fontSize:13,fontWeight:800}}><span>自己想一個：</span><input value={customValue} maxLength={30} onChange={(e) => onCustom(e.target.value)} placeholder="輸入短短的詞語，例如：小狐狸"/></label></fieldset>; }
function PromptCard({ number, title, text, copied, onCopy }: { number:string; title:string; text:string; copied:boolean; onCopy:()=>void }) { return <article className="prompt-card"><span className="number">{number}</span><div><h3>{title}</h3><p>{text}</p><button onClick={onCopy}>{copied ? "✓ 已複製！" : "複製提示詞"}</button></div></article>; }
